import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import Image from "next/image";
import developer from "../public/developer.png";
import code from "../public/code.png";
import design from "../public/design.png";
import software from "../public/software.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import React from "react";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Dakshay Ahuja</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className="bg-zinc-50 px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-9 mb12 flex justify-between dark:text-white">
            <BsFillMoonStarsFill
              className=" cursor-pointer text-2xl"
              onClick={() => setDarkMode(!darkMode)}
            />
            <a
              className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
              href="https://drive.google.com/file/d/16HYZLhuZGo7i0zRfTt_exMoyVX0YwgZS/view?usp=sharing"
              target="_blank"
            >
              Resume
            </a>
          </nav>

          <div className="text-center py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Dakshay Ahuja
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Front End Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-700 dark:text-gray-200 md:text-xl max-w-xl mx-auto">
              Software developer eager to tackle web development/design
              challenges to achieve lasting impacts on user experience.
            </p>
          </div>

          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a
              href="http://twitter.com/dakshayahuja"
              target="_blank"
              className="hover:text-cyan-800"
            >
              <AiFillTwitterCircle />
            </a>
            <a
              href="http://linkedin.com/in/dakshayahuja/"
              target="_blank"
              className="hover:text-cyan-800"
            >
              <AiFillLinkedin />
            </a>
            <a
              href="http://github.com/dakshayahuja"
              target="_blank"
              className="hover:text-cyan-800"
            >
              <AiFillGithub />
            </a>
          </div>

          <div className="relative mx-auto w-64 h-w-64 mt-12 mb-12 overflow-hidden md:h-72 md:w-72">
            <Image src={developer} />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-4xl py-1 dark:text-white">My Skills</h3>
            <p className="text-md py-2 leading-8 text-gray-700 dark:text-gray-200 md:text-lg">
              Completed a professional training of full stack development with
              hands-on projects which included the technologies like html, css,
              javascript, bootstrap, react, networking, database management and
              cloud computing.
            </p>
          </div>

          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image
                src={design}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-xl font-medium pt-8 pb-4">Web Development</h3>
              <p className="text-gray-800 py-1">HTML + CSS</p>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">React.JS</p>
              <p className="text-gray-800 py-1">Bootstrap, Tailwind</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} className="mx-auto" />
              <h3 className="text-xl font-medium pt-8 pb-4">Core</h3>
              <p className="text-gray-800 py-1">C++</p>
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1">OOPS with Java</p>
              <p className="text-gray-800 py-1">DBMS(mySQL, MongoDB)</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image
                src={software}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-xl font-medium pt-8 pb-4">Other</h3>
              <p className="text-gray-800 py-1">Networking</p>
              <p className="text-gray-800 py-1">Microsoft Office</p>
              <p className="text-gray-800 py-1">Operating Systems</p>
              <p className="text-gray-800 py-1">Cloud Computing(AWS,GCP)</p>
            </div>
          </div>
        </section>

        <section>
          <h3 className="text-4xl pt-10 dark:text-white">My Portfolio</h3>
          <div className="flex flex-col gap-10 py-5 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 border-2 border-gray-100 shadow-lg dark:border-0">
              <a href="http://fleecebag.netlify.app" target="_blank">
                <Image
                  src={web1}
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1 border-2 border-gray-100 shadow-lg dark:border-0">
              <a href="http://googlestoreclone.netlify.app" target="_blank">
                <Image
                  src={web2}
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1 border-2 border-gray-100 shadow-lg dark:border-0">
              <a
                href="https://aplusautomotive.netlify.app"
                target="_blank"
              >
                <Image
                  src={web3}
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1 border-2 border-gray-100 shadow-lg dark:border-0">
              <a
                href="https://github.com/dakshayahuja/Bullseye"
                target="_blank"
              >
                <Image
                  src={web4}
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                />
              </a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
